[providers]
python = "3.11"
node = "18"

[variables]
PYTHON_VERSION = "3.11"
NODE_VERSION = "18"

[build]
cmds = ["./deploy-unified.sh"]

[start]
cmd = "gunicorn RevolutionMVP_Django.wsgi --log-file - --bind 0.0.0.0:$PORT"

